services:
    laravel:
        build:
            context: ./docker/laravel-app
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        networks:
            - telegram-mediator-network

    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - laravel
        ports:
            - "80:80"
        profiles:
            - local
        networks:
            - telegram-mediator-network

    nginx-certbot:
        restart: unless-stopped
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        environment:
            - EMAIL=${EMAIL_FOR_SSL}
            - DOMAIN=${DOMAINS_FOR_SSL}
            - PHP_FPM_HOST=laravel
            - PHP_FPM_PORT=9000
        depends_on:
            - laravel
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
        profiles:
            - production
        networks:
            - telegram-mediator-network

networks:
    telegram-mediator-network:
        driver: bridge
